name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up JDK 1.9
        uses: actions/setup-java@v2
        with:
          java-version: '9.0.4'
          distribution: 'adopt-openj9'
      - name: Build, check and publish
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew -PBUILD_RELEASE publish
